# Generated by Django 4.2 on 2024-04-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0021_contact_var_contact_var2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='names',
        ),
    ]
